wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/projet_2/testemp.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1670345051.089347
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 22
      - 23
      - 35
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
env_name:
  desc: null
  value: CartPole-v1
policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 25000
